sudo: required
dist: trusty
language: csharp
mono: none
dotnet: 1.0.0-preview2-003121
node_js: 6
install:
    - npm install
    - dotnet restore
script:
    - npm run build
    - dotnet build
    - dotnet publish
