name: Docker
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 6' # every Saturday
  workflow_dispatch:

jobs:
  push:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: codingteam/codingteam.org.ru
          tag_with_ref: true
          tags: latest
          push: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') && 'true' || 'false' }}
